[SGB]
GBBIOSEnabled = FALSE
GBBootPolicy = 2

[BIOS]
SGB1 = {sgb1_bios}
SGB1BootROM = {sgb1_boot_rom}

[Display]
MessagesInImage = FALSE
MessageDisplayTime = 0
BlendGBFrames = 0
BlendGBFramesAuto = FALSE

[Display\Win]
FilterType = 0
Window:Width = 264
Window:Height = 252
Window:SizedFor = 0
Stretch:Enabled = FALSE
Stretch:BilinearFilter = FALSE
HideMenu = TRUE
Vsync = FALSE

[Settings\Win]
PauseWhenInactive = FALSE
AddToRegistry = FALSE
