[SGB]
GBBIOSEnabled = FALSE
GBBootPolicy = 0

[Display]
MessagesInImage = FALSE
MessageDisplayTime = 0
BlendGBFrames = 0
BlendGBFramesAuto = FALSE

[Display\Win]
FilterType = 0
Window:Width = 168
Window:Height = 172
Stretch:Enabled = FALSE
Stretch:BilinearFilter = FALSE
HideMenu = TRUE
Vsync = FALSE

[Settings\Win]
PauseWhenInactive = FALSE
AddToRegistry = FALSE
